apiVersion: v1
kind: Config
preferences:
  colors: true
current-context: tf-k8s-gcp
contexts:
- context:
    cluster: ${cluster_name}
    namespace: default
    user: user
  name: tf-k8s-gcp
clusters:
- cluster:
    server: https://${endpoint}
    certificate-authority-data: ${cluster_ca}
  name: ${cluster_name}
users:
- name: user
  user:
    token: "${token}"